dist/components/HeaderComponent.js
src/components/HeaderComponent.ts

fix padding issue for header component inside a container
Refs: [#issue-2634457275]
---
- Closes #issue-2634457275 (if applicable)
---

fix: fix padding issue

---

dist/components/ContainerComponent.js
src/components/ContainerComponent.ts

**Fix: Duplicate Components Inside Restored Container Issue**
---
This PR addresses an issue where duplicate components were being created inside restored containers after the restoration process. The changes ensure:
- Components within containers are restored without duplication.
- Unique identifiers are validated during restoration to prevent adding the same component multiple times.
- Closes #456 (example issue reference, replace with the actual issue number if applicable)
- Before: Containers restored with duplicated components.
- After: Containers restored with unique components only.
To fix the issue:
1. **Validation Before Adding …

fix: fix the duplicate component inside restored container issue

---

dist/canvas/Canvas.d.ts
dist/canvas/Canvas.js
dist/canvas/ComponentControls.d.ts
dist/canvas/ComponentControls.js
dist/components/ContainerComponent.d.ts
dist/components/ContainerComponent.js
src/canvas/Canvas.ts
src/canvas/ComponentControls.ts
src/components/ContainerComponent.ts

**Fix: Nested Container Issues**
---
This PR resolves the following issues with nested containers:
1. **Container Resizer Not Working**: Resizer functionality was broken for containers nested inside a restored container.
2. **Deleting Child Components**: Deletion of child components within restored containers was not functioning correctly.
3. **Child Label Not Displaying**: Labels for child components inside restored containers were not being shown on hover.
- Closes #ISSUE_NUMBER
- Before:
- Resizer not functional for nested containers in restored state.
- Deletion of child components not working inside restored containers.
- Child labels not displaying on hover.
- After:
- Resizer works seamlessly for nested …

fix: fix nested container issues

---

dist/services/HTMLGenerator.js
src/services/HTMLGenerator.ts

remove image upload button in preview
Refs:[]
---
---

fix: remove image upload button in preview

---

dist/sidebar/CustomizationSidebar.js
dist/utils/utilityFunctions.d.ts
dist/utils/utilityFunctions.js
src/sidebar/CustomizationSidebar.ts
src/utils/utilityFunctions.ts

**Fix undo and redo for styles for each component**
---
This PR addresses the issue of undo and redo functionality for the styles of individual components within the canvas. It ensures that style changes made to components (such as resizing, positioning, or other style modifications) can be undone and redone effectively, providing a better user experience for editing components.
---

fix: fix undo redo for styles

---

dist/index.js
src/index.ts
src/styles/main.css

**fix: fix position of export button**
---
This PR fixes the positioning of the export button to ensure it is properly aligned and accessible in the user interface, improving the overall user experience.
---

fix: fix position of export button

---

dist/canvas/ComponentControls.d.ts
dist/canvas/ComponentControls.js
src/canvas/ComponentControls.ts
src/styles/main.css

**fix: fix duplication of component control div**
---
This PR addresses the duplication issue of the component controls `div`, ensuring that only a single instance of the controls is added to each component. This enhances performance and prevents UI clutter.
---

fix: fix duplication of component control div

---

dist/canvas/ComponentControls.js
src/canvas/ComponentControls.ts

Fix duplicate controls div for container reload
Refs:[]
---
---

fix: fix duplicate controls div for container

---

dist/components/ContainerComponent.d.ts
dist/components/ContainerComponent.js
src/components/ContainerComponent.ts

**fix: fix the state capturing of container resizer**
---
Fixes the state capturing for the undo/redo feature of the container resizer, ensuring accurate restoration of component states during resizing actions.
---

fix: fix the state capturing of container resizer

---

dist/services/HTMLGenerator.js
dist/styles/main.css
src/services/HTMLGenerator.ts
src/styles/main.css

**fix: fix reflection of input element in exported html**
---
Fixes the reflection of input elements in the exported HTML and addresses the fluctuation issue of the sidebar during export. This ensures that the exported HTML properly represents the input elements and maintains sidebar stability.
---

fix: fix reflection of input element in exported html

---

dist/components/TwoColumnComponent.js
dist/index.js
dist/sidebar/CreateSidebar.js
dist/styles/main.css
src/index.ts
src/sidebar/CreateSidebar.ts
src/styles/main.css

feat(sidebar): add title to sidebar and close button to export zip modal

---

dist/canvas/ComponentControls.d.ts
dist/canvas/ComponentControls.js
dist/components/ContainerComponent.js
dist/components/TwoColumnComponent.js
dist/styles/main.css
src/canvas/ComponentControls.ts
src/components/ContainerComponent.ts
src/styles/main.css

Fix the delete functionality for multicolumn components and resolve the sidebar issue.
---
- Fixes the delete functionality for multicolumn components.
- Resolves the issue with the sidebar display and behavior.
- Refs: []
---

fix: fix delete functionality and sidebar issue

---

dist/canvas/Canvas.js
dist/components/ButtonComponent.d.ts
dist/components/ButtonComponent.js
dist/components/HeaderComponent.d.ts
dist/components/HeaderComponent.js
dist/components/TextComponent.d.ts
dist/components/TextComponent.js
dist/components/TwoColumnComponent.js
dist/sidebar/CreateSidebar.js
src/canvas/Canvas.ts
src/components/ButtonComponent.ts
src/components/HeaderComponent.ts
src/components/TextComponent.ts
src/sidebar/CreateSidebar.ts

Fixed resizable issue for the button, header and text component
---
This PR Fixed the resizable issue for the button, header and text component. before they are not able to resize but now it is working.
---

fix(resizable issue): button, text, header resizable issue

---

dist/components/TwoColumnComponent.js
dist/sidebar/CreateSidebar.js
dist/styles/main.css
src/sidebar/CreateSidebar.ts
src/styles/main.css

##Fix spacing around category heading
**Fix spacing around category heading.**
---
This PR fixes the awkward spacing around category heading
---

fix: fix spacing around category heading

---

packages/core/dist/components/TwoColumnComponent.js
packages/core/dist/index.js
packages/core/src/index.ts

**Icons for responsive configuration at view section was not appearing**
---
_It resolves the icons issue for view section and places the icon svgs at their respective places_
---

fix: fix icons section for view

---

.changeset/brown-penguins-cheer.md
.changeset/quiet-parrots-hear.md
.changeset/ten-flies-flow.md
packages/core/CHANGELOG.md
packages/core/package.json
packages/react/CHANGELOG.md
packages/react/package.json

chore: version packages

---

.changeset/sharp-walls-repeat.md
packages/react/CHANGELOG.md
packages/react/package.json

chore(release): version packages

---

packages/example/test-angular/package.json
packages/example/test-react-web/src/App.jsx

**This pr is to release the latest version web-component of page-builder**
---
_Release new version._
- [] 🐛 Bug fix
---

Release web-component

---

documentation/docs/Getting-started/react.md

- Updated documentation to include details on **custom components**.
- Added sections explaining how users can create **custom components** with:
- **Configurable properties** (title, icon, settings).
- **Integration with the sidebar** for seamless usage.
- **Persistence across sessions**.
- Improved clarity on **dynamic components**, explaining:
- How they adapt to user-defined configurations.
- Their behavior inside the existing component system.
- Included examples and code snippets for better understanding.
---
- Enhances the documentation for **custom and dynamic components**.
- Provides a clear guide on integrating user-defined components into the system.
- Adds structured examples and explanations for developers.
- Refs: []
_Please ensure the following have been completed before …

docs(react): update docs related to custom and dynamic components

---

packages/react/README.md

**Update readme file of react wrapper**
---
Update readme file of react wrapper
---

docs(react): update readme file of react wrapper
